export const APP_ROUTES = {
  HOME: "/",
  RESULTS: "/results",
  CAR_DETAILS: "/car-details/:id",
  PAYMENT: "/payment",
  BOOKING_SUCCESS: "/booking-success",
  PROFILE: "/profile",
  OWNER_DASHBOARD: "/dashboard/owner",
  ADMIN_DASHBOARD: "/dashboard/admin",
  ADMIN_USERS: "/dashboard/admin/users",
  ADMIN_BOOKINGS: "/dashboard/admin/bookings",
  ADMIN_PAYMENTS: "/dashboard/admin/payments",
  ADMIN_REVIEWS: "/dashboard/admin/reviews",
  PROFILE_VERIFICATION: "/profile/verification",
};
