export const APP_ROUTES = {
  HOME: "/",
  RESULTS: "/results",
  CAR_DETAILS: "/car-details/:id",
  OWNER_REGISTER: "/owner/register",
  PAYMENT: "/payment",
  PAYMENT_SUCCESS: "/payment/success",
  PAYMENT_CANCEL: "/payment/cancel",
  BOOKING_SUCCESS: "/booking-success",
  PROFILE: "/profile",
  OWNER_DASHBOARD: "/dashboard/owner",
  ADMIN_DASHBOARD: "/dashboard/admin",
  ADMIN_CARS: "/dashboard/admin/cars",
  ADMIN_USERS: "/dashboard/admin/users",
  ADMIN_OWNERS: "/dashboard/admin/owners",
  ADMIN_BOOKINGS: "/dashboard/admin/bookings",
  ADMIN_LICENSES: "/dashboard/admin/licenses",
  ADMIN_PAYMENTS: "/dashboard/admin/payments",
  ADMIN_REVIEWS: "/dashboard/admin/reviews",
  ADMIN_PROMOTIONS: "/dashboard/admin/promotions",
  PROFILE_VERIFICATION: "/profile/verification",
};
