spring:
  application:
    name: car-rental
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=car_rental;encrypt=false;trustServerCertificate=true
    username: sa
    password: Sql@123456
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  flyway:
    enabled: true
    locations: classpath:db/migration
    out-of-order: true
  mail:
    from: ${MAIL_USERNAME}
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true


jwt:
  limit:
    day: 15
    hour: 1
  secretKey: iEKeAbUUiOb/waueS/nKrEV4aAEtrO5LZoVq+8fk8XHgXFmMUT70euKykS3JI0yzOAelB167lBKavBiQIRf9UQ==
  refreshKey: 6m08koVwpxvdnLpSRDdLOcLjL+xAgbCgMQ9dX09E1sZMIvW0oDqpTlqgICvxDAcg1y8N1Q4M2QT0Pxux7Lu4Pw==
cloudinary:
  cloud-name: dejiclsce
  api-key: 521862237379554
  api-secret: zL1J83JXhXBDf2qg3NmtOE8caU4
logging:
  level:
    org:
        hibernate:
          SQL: debug
          orm:
            jdbc:
              bind: TRACE
